feat: react example and PR pipeline
Hyphen/openfeature-provider-javascript-web pull request #5
Opened 2024-12-09 18:22 UTC by cialese

- [x] Contains example of how to consume the provider
	- [x] These should exist in an examples folder
	- [x] These should be excluded from any packaged content (NPM package, etc.)
- [x] CI/CD Pipeline
	- [x] PR pipeline (build, lint, test)

2024-12-31 15:40 UTC, osbornm commented
Let's use the example that I sent in slack. We need to clean it up a bit but it way more realistic to have a authProvider that sets the context and then use the openfeature hooks through out the pages.

2025-01-03 15:45 UTC, osbornm commented
@cialese is this ready for review again? if not when will it be?

2025-01-03 16:06 UTC, cialese commented
> @cialese is this ready for review again? if not when will it be?

I already have a working example using the web sdk and auth, I'll have today the example using the react sdk

2025-01-06 16:04 UTC, osbornm requested changes

2025-01-06 16:04 UTC, osbornm commented on examples/react-example/.gitignore
> +# Logs
Do we want this just in the root?

2025-01-06 16:04 UTC, osbornm commented on examples/react-example/src/App.tsx
> +    ipAddress: '203.0.113.42',
We should show how to get this.

2025-01-06 16:04 UTC, osbornm commented on examples/react-example/src/App.tsx
> +        await OpenFeature.setContext(context);
I would say it would be best practice to use a provider for this. We should do that with our example.

2025-01-06 16:04 UTC, osbornm commented on README.md
> + - Have access to a valid Hyphen Toggle publicKey and application details.
```suggestion
 - Have access to a valid Hyphen publicKey and application details.
```

2025-01-06 16:04 UTC, osbornm commented on README.md
> +    const isEnabled = client.getStringDetails('your-flag-key', 'default value');
Let's just show the setContext call. They can go into the example to see the whole thing.

2025-01-06 16:04 UTC, osbornm commented on src/provider.ts
> +    console.log('afterHook', hookContext, evaluationDetails);
```suggestion
```

2025-01-06 16:04 UTC, osbornm commented on src/provider.ts
> +    console.log('evaluationResponse', evaluationResponse);
```suggestion
```

2025-01-06 16:04 UTC, osbornm commented on src/provider.ts
> +    console.log('onContextChange', oldContext, newContext);
```suggestion
```

2025-01-06 16:04 UTC, osbornm commented on src/provider.ts
> +    console.log('evaluation', evaluation);
```suggestion
```

2025-01-06 21:29 UTC, osbornm approved these changes

2025-01-06 21:44 UTC, merged